import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import MenuTab from "./home/(components)/MenuTab";
import Header from "@/components/UiComponents/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainComponentLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="bg-main-bg min-h-screen relative flex flex-col">
    
        

          <div className="flex-1"> {children}</div>

          <div className="fixed bottom-0 left-0 right-0">
            <MenuTab />
          </div>
        </main>
      </body>
    </html>
  );
}
